FROM keymetrics/pm2:8-jessie

# Bundle APP files
COPY server /app/server/
COPY vcnt_server.config.js /app

# Create app directory
WORKDIR /app

# Install app dependencies
RUN cd server && npm install
RUN cd ..

# Expose the listening port of your app
EXPOSE 3000

# Show current folder structure in logs
# RUN ls -al -R

CMD ["pm2-runtime", "--env", "development" , "start", "vcnt_server.config.js"]
